# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jx@19940228
    filters: wall,mergeStat
    data-source-name: gunsdb

# 多数据源情况的配置
guns:
  muti-datasource:
    open: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jx@19940228
    data-source-name: otherdb
